---
version: 2

registries:
  github-ntc:
    type: git
    url: https://github.com
    username: dependabot
    password: ${{ secrets.GHE_API_TOKEN }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/"
    registries:
      - github-ntc
    schedule:
      interval: "daily"