name: TERRAFORM VCS

on:
  pull_request:
    branches:
      - main
  # push:
  #   branches:
  #     - main

jobs:
  terraform-vcs:
    uses: nuvibit/github-terraform-workflows/.github/workflows/terraform-vcs.yml@v1
    with:
      tflint_repo: "nuvibit/github-tflint-config"
      tflint_repo_config_path: "aws/.tflint_ntc.hcl"
    secrets:
      GHE_API_TOKEN: ${{ secrets.GHE_API_TOKEN }}